#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

. script/commands

echo "==> Installing gem dependencies…"
$cmdprefix bundle check --path vendor/gems 2>&1 > /dev/null || {
  $cmdprefix bundle install --path vendor/gems --quiet --without production
}
