#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update "$@"

test -z "$RACK_ENV" &&
  RACK_ENV='development'

# boot the app and any other necessary processes.
if [ -n "$1" && "$1" == "docker" ]; then
  docker-compose up web
else
  foreman start -p 9393
fi
