#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap "$@"

. script/commands "$@"

echo "==> Updating db..."
# run all database migrations to ensure everything is up to date.
$rake_cmd db:create db:migrate
